// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

type Block struct {
	BlockNumber int64
	BlockHash   []byte
	ParentHash  []byte
	Timestamp   int64
	ExtraData   []byte
}

type Log struct {
	BlockNumber int64
	TxHash      []byte
	TxIndex     int64
	LogIndex    int64
	Address     []byte
	Topic0      []byte
	Topic1      []byte
	Topic2      []byte
	Topic3      []byte
	Data        []byte
}

type Transaction struct {
	TxHash          []byte
	BlockHash       []byte
	BlockNumber     int64
	TxIndex         int64
	RawTx           []byte
	FromAddress     []byte
	ToAddress       []byte
	ContractAddress []byte
	Status          int64
	FabricTxID      string
	FabricTxStatus  int64
}
