// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title Ownable
 */
contract Ownable {
    address public owner;
    constructor() {
        owner = msg.sender;
    }
    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }
    function transferOwnership(address newOwner) public onlyOwner {
        require(newOwner != address(0), "Zero address");
        owner = newOwner;
    }
}

/**
 * @title ERC20Basic
 */
abstract contract ERC20Basic {
    uint256 internal _totalSupply; // made non-public to avoid autogenerated getter collision
    function totalSupply() public view virtual returns (uint256);
    function balanceOf(address who) public view virtual returns (uint256);
    function transfer(address to, uint256 value) public virtual;
    event Transfer(address indexed from, address indexed to, uint256 value);
}

/**
 * @title ERC20 interface
 */
abstract contract ERC20 is ERC20Basic {
    function allowance(address owner, address spender) public view virtual returns (uint256);
    function transferFrom(address from, address to, uint256 value) public virtual;
    function approve(address spender, uint256 value) public virtual;
    event Approval(address indexed owner, address indexed spender, uint256 value);
}

/**
 * @title Basic token
 */
abstract contract BasicToken is Ownable, ERC20Basic {
    mapping(address => uint256) public balances;
    uint256 public basisPointsRate = 0;
    uint256 public maximumFee = 0;

    modifier onlyPayloadSize(uint256 size) {
        require(msg.data.length >= size + 4, "Short payload");
        _;
    }

    function transfer(address _to, uint256 _value)
        public virtual override onlyPayloadSize(2 * 32)
    {
        uint256 fee = (_value * basisPointsRate) / 10000;
        if (fee > maximumFee) {
            fee = maximumFee;
        }
        uint256 sendAmount = _value - fee;
        balances[msg.sender] -= _value;
        balances[_to] += sendAmount;
        if (fee > 0) {
            balances[owner] += fee;
            emit Transfer(msg.sender, owner, fee);
        }
        emit Transfer(msg.sender, _to, sendAmount);
    }

    function balanceOf(address _owner)
        public view virtual override returns (uint256 balance)
    {
        return balances[_owner];
    }
}

/**
 * @title Standard ERC20 token
 */
contract StandardToken is BasicToken, ERC20 {
    mapping (address => mapping (address => uint256)) public allowed;
    uint256 public constant MAX_UINT = type(uint256).max;

    function transferFrom(address _from, address _to, uint256 _value)
        public virtual override onlyPayloadSize(3 * 32)
    {
        uint256 _allowance = allowed[_from][msg.sender];

        // Check allowance first
        require(_allowance >= _value || _allowance == MAX_UINT, "transferFrom: allowance too low");
        
        uint256 fee = (_value * basisPointsRate) / 10000;
        if (fee > maximumFee) {
            fee = maximumFee;
        }
        if (_allowance < MAX_UINT) {
            allowed[_from][msg.sender] = _allowance - _value;
        }
        uint256 sendAmount = _value - fee;
        balances[_from] -= _value;
        balances[_to] += sendAmount;
        if (fee > 0) {
            balances[owner] += fee;
            emit Transfer(_from, owner, fee);
        }
        emit Transfer(_from, _to, sendAmount);
    }

    function approve(address _spender, uint256 _value)
        public virtual override onlyPayloadSize(2 * 32)
    {
        require((_value == 0) || (allowed[msg.sender][_spender] == 0), "Must set to zero first");
        allowed[msg.sender][_spender] = _value;
        emit Approval(msg.sender, _spender, _value);
    }

    function allowance(address _owner, address _spender)
        public view virtual override returns (uint256 remaining)
    {
        return allowed[_owner][_spender];
    }

    function totalSupply()
        public view virtual override returns (uint256)
    {
        return _totalSupply;
    }
}

/**
 * @title Pausable
 */
contract Pausable is Ownable {
    event Pause();
    event Unpause();

    bool public paused = false;

    modifier whenNotPaused() {
        require(!paused, "Paused");
        _;
    }

    modifier whenPaused() {
        require(paused, "Not paused");
        _;
    }

    function pause() public onlyOwner whenNotPaused {
        paused = true;
        emit Pause();
    }

    function unpause() public onlyOwner whenPaused {
        paused = false;
        emit Unpause();
    }
}

/**
 * @title BlackList
 */
abstract contract BlackList is Ownable, BasicToken {
    mapping (address => bool) public isBlackListed;

    function getBlackListStatus(address _maker) external view returns (bool) {
        return isBlackListed[_maker];
    }

    function getOwner() external view returns (address) {
        return owner;
    }

    function addBlackList(address _evilUser) public onlyOwner {
        isBlackListed[_evilUser] = true;
        emit AddedBlackList(_evilUser);
    }

    function removeBlackList(address _clearedUser) public onlyOwner {
        isBlackListed[_clearedUser] = false;
        emit RemovedBlackList(_clearedUser);
    }

    function destroyBlackFunds(address _blackListedUser) public onlyOwner {
        require(isBlackListed[_blackListedUser], "Not blacklisted");
        uint256 dirtyFunds = balanceOf(_blackListedUser);
        balances[_blackListedUser] = 0;
        _totalSupply -= dirtyFunds;
        emit DestroyedBlackFunds(_blackListedUser, dirtyFunds);
    }

    event DestroyedBlackFunds(address _blackListedUser, uint256 _balance);
    event AddedBlackList(address _user);
    event RemovedBlackList(address _user);
}

/**
 * @title UpgradedStandardToken
 */
abstract contract UpgradedStandardToken is StandardToken {
    function transferByLegacy(address from, address to, uint256 value) public virtual;
    function transferFromByLegacy(address sender, address from, address to, uint256 value) public virtual;
    function approveByLegacy(address from, address spender, uint256 value) public virtual;
}

/**
 * @title TetherToken
 */
contract TetherToken is Pausable, StandardToken, BlackList {
    string public name;
    string public symbol;
    uint256 public decimals;
    address public upgradedAddress;
    bool public deprecated;

    event Issue(uint256 amount);
    event Redeem(uint256 amount);
    event Deprecate(address newAddress);
    event Params(uint256 feeBasisPoints, uint256 maxFee);

    constructor(uint256 _initialSupply, string memory _name, string memory _symbol, uint256 _decimals) {
        _totalSupply = _initialSupply;
        name = _name;
        symbol = _symbol;
        decimals = _decimals;
        balances[owner] = _initialSupply;
        deprecated = false;
    }

    function transfer(address _to, uint256 _value)
        public override(BasicToken, ERC20Basic) whenNotPaused
    {
        require(!isBlackListed[msg.sender], "Sender is blacklisted");
        if (deprecated) {
            UpgradedStandardToken(upgradedAddress).transferByLegacy(msg.sender, _to, _value);
        } else {
            BasicToken.transfer(_to, _value);
        }
    }

    function transferFrom(address _from, address _to, uint256 _value)
        public override(StandardToken) whenNotPaused
    {
        require(!isBlackListed[_from], "From is blacklisted");
        if (deprecated) {
            UpgradedStandardToken(upgradedAddress).transferFromByLegacy(msg.sender, _from, _to, _value);
        } else {
            StandardToken.transferFrom(_from, _to, _value);
        }
    }

    function balanceOf(address who)
        public view override(BasicToken, ERC20Basic) returns (uint256)
    {
        if (deprecated) {
            return UpgradedStandardToken(upgradedAddress).balanceOf(who);
        } else {
            return BasicToken.balanceOf(who);
        }
    }

    function approve(address _spender, uint256 _value)
        public override(StandardToken) onlyPayloadSize(2 * 32)
    {
        if (deprecated) {
            UpgradedStandardToken(upgradedAddress).approveByLegacy(msg.sender, _spender, _value);
        } else {
            StandardToken.approve(_spender, _value);
        }
    }

    function allowance(address _owner, address _spender)
        public view override(StandardToken) returns (uint256 remaining)
    {
        if (deprecated) {
            return StandardToken(upgradedAddress).allowance(_owner, _spender);
        } else {
            return StandardToken.allowance(_owner, _spender);
        }
    }

    function deprecate(address _upgradedAddress) public onlyOwner {
        deprecated = true;
        upgradedAddress = _upgradedAddress;
        emit Deprecate(_upgradedAddress);
    }

    function totalSupply()
        public view override(StandardToken, ERC20Basic) returns (uint256)
    {
        if (deprecated) {
            return StandardToken(upgradedAddress).totalSupply();
        } else {
            return _totalSupply;
        }
    }

    function issue(uint256 amount) public onlyOwner {
        require(_totalSupply + amount > _totalSupply, "Overflow");
        require(balances[owner] + amount > balances[owner], "Overflow");

        balances[owner] += amount;
        _totalSupply += amount;
        emit Issue(amount);
    }

    function redeem(uint256 amount) public onlyOwner {
        require(_totalSupply >= amount, "Exceeds supply");
        require(balances[owner] >= amount, "Exceeds balance");

        _totalSupply -= amount;
        balances[owner] -= amount;
        emit Redeem(amount);
    }

    function setParams(uint256 newBasisPoints, uint256 newMaxFee) public onlyOwner {
        require(newBasisPoints < 20, "too large");
        require(newMaxFee < 50, "too large");

        basisPointsRate = newBasisPoints;
        maximumFee = newMaxFee * (10 ** decimals);

        emit Params(basisPointsRate, maximumFee);
    }
}
