//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/endorsementpb/endorsement.proto

package endorsementpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EvmEndorsement_Execute_FullMethodName   = "/endorsementpb.EvmEndorsement/Execute"
	EvmEndorsement_Call_FullMethodName      = "/endorsementpb.EvmEndorsement/Call"
	EvmEndorsement_BalanceAt_FullMethodName = "/endorsementpb.EvmEndorsement/BalanceAt"
	EvmEndorsement_StorageAt_FullMethodName = "/endorsementpb.EvmEndorsement/StorageAt"
	EvmEndorsement_CodeAt_FullMethodName    = "/endorsementpb.EvmEndorsement/CodeAt"
	EvmEndorsement_NonceAt_FullMethodName   = "/endorsementpb.EvmEndorsement/NonceAt"
)

// EvmEndorsementClient is the client API for EvmEndorsement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EvmEndorsement is the endorser's API: one RPC per engine function. Execute is
// the only RPC that returns an endorsement; the reads return plain values.
type EvmEndorsementClient interface {
	// Execute endorses an Ethereum transaction.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// Call runs a read-only eth_call.
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	BalanceAt(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	StorageAt(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*StorageResponse, error)
	CodeAt(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeResponse, error)
	NonceAt(ctx context.Context, in *NonceRequest, opts ...grpc.CallOption) (*NonceResponse, error)
}

type evmEndorsementClient struct {
	cc grpc.ClientConnInterface
}

func NewEvmEndorsementClient(cc grpc.ClientConnInterface) EvmEndorsementClient {
	return &evmEndorsementClient{cc}
}

func (c *evmEndorsementClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, EvmEndorsement_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evmEndorsementClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, EvmEndorsement_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evmEndorsementClient) BalanceAt(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, EvmEndorsement_BalanceAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evmEndorsementClient) StorageAt(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*StorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageResponse)
	err := c.cc.Invoke(ctx, EvmEndorsement_StorageAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evmEndorsementClient) CodeAt(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeResponse)
	err := c.cc.Invoke(ctx, EvmEndorsement_CodeAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evmEndorsementClient) NonceAt(ctx context.Context, in *NonceRequest, opts ...grpc.CallOption) (*NonceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NonceResponse)
	err := c.cc.Invoke(ctx, EvmEndorsement_NonceAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EvmEndorsementServer is the server API for EvmEndorsement service.
// All implementations must embed UnimplementedEvmEndorsementServer
// for forward compatibility.
//
// EvmEndorsement is the endorser's API: one RPC per engine function. Execute is
// the only RPC that returns an endorsement; the reads return plain values.
type EvmEndorsementServer interface {
	// Execute endorses an Ethereum transaction.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// Call runs a read-only eth_call.
	Call(context.Context, *CallRequest) (*CallResponse, error)
	BalanceAt(context.Context, *BalanceRequest) (*BalanceResponse, error)
	StorageAt(context.Context, *StorageRequest) (*StorageResponse, error)
	CodeAt(context.Context, *CodeRequest) (*CodeResponse, error)
	NonceAt(context.Context, *NonceRequest) (*NonceResponse, error)
	mustEmbedUnimplementedEvmEndorsementServer()
}

// UnimplementedEvmEndorsementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEvmEndorsementServer struct{}

func (UnimplementedEvmEndorsementServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedEvmEndorsementServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedEvmEndorsementServer) BalanceAt(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BalanceAt not implemented")
}
func (UnimplementedEvmEndorsementServer) StorageAt(context.Context, *StorageRequest) (*StorageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StorageAt not implemented")
}
func (UnimplementedEvmEndorsementServer) CodeAt(context.Context, *CodeRequest) (*CodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CodeAt not implemented")
}
func (UnimplementedEvmEndorsementServer) NonceAt(context.Context, *NonceRequest) (*NonceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NonceAt not implemented")
}
func (UnimplementedEvmEndorsementServer) mustEmbedUnimplementedEvmEndorsementServer() {}
func (UnimplementedEvmEndorsementServer) testEmbeddedByValue()                        {}

// UnsafeEvmEndorsementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EvmEndorsementServer will
// result in compilation errors.
type UnsafeEvmEndorsementServer interface {
	mustEmbedUnimplementedEvmEndorsementServer()
}

func RegisterEvmEndorsementServer(s grpc.ServiceRegistrar, srv EvmEndorsementServer) {
	// If the following call panics, it indicates UnimplementedEvmEndorsementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EvmEndorsement_ServiceDesc, srv)
}

func _EvmEndorsement_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvmEndorsementServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvmEndorsement_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvmEndorsementServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvmEndorsement_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvmEndorsementServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvmEndorsement_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvmEndorsementServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvmEndorsement_BalanceAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvmEndorsementServer).BalanceAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvmEndorsement_BalanceAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvmEndorsementServer).BalanceAt(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvmEndorsement_StorageAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvmEndorsementServer).StorageAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvmEndorsement_StorageAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvmEndorsementServer).StorageAt(ctx, req.(*StorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvmEndorsement_CodeAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvmEndorsementServer).CodeAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvmEndorsement_CodeAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvmEndorsementServer).CodeAt(ctx, req.(*CodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvmEndorsement_NonceAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvmEndorsementServer).NonceAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvmEndorsement_NonceAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvmEndorsementServer).NonceAt(ctx, req.(*NonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EvmEndorsement_ServiceDesc is the grpc.ServiceDesc for EvmEndorsement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EvmEndorsement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "endorsementpb.EvmEndorsement",
	HandlerType: (*EvmEndorsementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _EvmEndorsement_Execute_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _EvmEndorsement_Call_Handler,
		},
		{
			MethodName: "BalanceAt",
			Handler:    _EvmEndorsement_BalanceAt_Handler,
		},
		{
			MethodName: "StorageAt",
			Handler:    _EvmEndorsement_StorageAt_Handler,
		},
		{
			MethodName: "CodeAt",
			Handler:    _EvmEndorsement_CodeAt_Handler,
		},
		{
			MethodName: "NonceAt",
			Handler:    _EvmEndorsement_NonceAt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/endorsementpb/endorsement.proto",
}
