//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/endorsementpb/endorsement.proto

package endorsementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Marshaled Ethereum transaction (types.Transaction.MarshalBinary).
	EthereumTx []byte `protobuf:"bytes,1,opt,name=ethereum_tx,json=ethereumTx,proto3" json:"ethereum_tx,omitempty"`
	// Proposal hash, required by classic Fabric because the submitted payload
	// must carry it. Fabric-X does not need the proposal, so this is empty
	// there and the full proposal never crosses the wire.
	ProposalHash  []byte `protobuf:"bytes,2,opt,name=proposal_hash,json=proposalHash,proto3" json:"proposal_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_endorsement_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetEthereumTx() []byte {
	if x != nil {
		return x.EthereumTx
	}
	return nil
}

func (x *ExecuteRequest) GetProposalHash() []byte {
	if x != nil {
		return x.ProposalHash
	}
	return nil
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized read-write set of the execution.
	ReadWriteSet []byte `protobuf:"bytes,1,opt,name=read_write_set,json=readWriteSet,proto3" json:"read_write_set,omitempty"`
	Event        []byte `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// Outcome of the execution: OK, revert, rejected, exec failure, or server
	// error. Application outcomes travel here, not as a gRPC error.
	Status  int32  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// Serialized identity of the endorser and its signature over the result.
	EndorserId    []byte `protobuf:"bytes,6,opt,name=endorser_id,json=endorserId,proto3" json:"endorser_id,omitempty"`
	Signature     []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_endorsement_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetReadWriteSet() []byte {
	if x != nil {
		return x.ReadWriteSet
	}
	return nil
}

func (x *ExecuteResponse) GetEvent() []byte {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteResponse) GetEndorserId() []byte {
	if x != nil {
		return x.EndorserId
	}
	return nil
}

func (x *ExecuteResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 20-byte address; empty when unset.
	From []byte `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// 20-byte address; empty for contract creation.
	To  []byte `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Gas uint64 `protobuf:"varint,3,opt,name=gas,proto3" json:"gas,omitempty"`
	// Big-endian integer bytes.
	GasPrice []byte `protobuf:"bytes,4,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Value    []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Data     []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// Absent means latest.
	BlockNumber   *uint64 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3,oneof" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_endorsement_proto_rawDescGZIP(), []int{2}
}

func (x *CallRequest) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CallRequest) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *CallRequest) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *CallRequest) GetGasPrice() []byte {
	if x != nil {
		return x.GasPrice
	}
	return nil
}

func (x *CallRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CallRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CallRequest) GetBlockNumber() uint64 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

type CallResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ReturnData []byte                 `protobuf:"bytes,1,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	// Set when the call did not succeed; carries the revert reason and payload.
	Status        int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_endorsement_proto_rawDescGZIP(), []int{3}
}

func (x *CallResponse) GetReturnData() []byte {
	if x != nil {
		return x.ReturnData
	}
	return nil
}

func (x *CallResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CallResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       []byte                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	BlockNumber   *uint64                `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3,oneof" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_endorsement_proto_rawDescGZIP(), []int{4}
}

func (x *BalanceRequest) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *BalanceRequest) GetBlockNumber() uint64 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

type BalanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Big-endian integer bytes.
	Balance       []byte `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_endorsement_proto_rawDescGZIP(), []int{5}
}

func (x *BalanceResponse) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

type StorageRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Account []byte                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// 32-byte storage key.
	Key           []byte  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	BlockNumber   *uint64 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3,oneof" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageRequest) Reset() {
	*x = StorageRequest{}
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageRequest) ProtoMessage() {}

func (x *StorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageRequest.ProtoReflect.Descriptor instead.
func (*StorageRequest) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_endorsement_proto_rawDescGZIP(), []int{6}
}

func (x *StorageRequest) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *StorageRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StorageRequest) GetBlockNumber() uint64 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

type StorageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32-byte storage word.
	Value         []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageResponse) Reset() {
	*x = StorageResponse{}
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageResponse) ProtoMessage() {}

func (x *StorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageResponse.ProtoReflect.Descriptor instead.
func (*StorageResponse) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_endorsement_proto_rawDescGZIP(), []int{7}
}

func (x *StorageResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       []byte                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	BlockNumber   *uint64                `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3,oneof" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeRequest) Reset() {
	*x = CodeRequest{}
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeRequest) ProtoMessage() {}

func (x *CodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeRequest.ProtoReflect.Descriptor instead.
func (*CodeRequest) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_endorsement_proto_rawDescGZIP(), []int{8}
}

func (x *CodeRequest) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *CodeRequest) GetBlockNumber() uint64 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

type CodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          []byte                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeResponse) Reset() {
	*x = CodeResponse{}
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeResponse) ProtoMessage() {}

func (x *CodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeResponse.ProtoReflect.Descriptor instead.
func (*CodeResponse) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_endorsement_proto_rawDescGZIP(), []int{9}
}

func (x *CodeResponse) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

type NonceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       []byte                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	BlockNumber   *uint64                `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3,oneof" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonceRequest) Reset() {
	*x = NonceRequest{}
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonceRequest) ProtoMessage() {}

func (x *NonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonceRequest.ProtoReflect.Descriptor instead.
func (*NonceRequest) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_endorsement_proto_rawDescGZIP(), []int{10}
}

func (x *NonceRequest) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *NonceRequest) GetBlockNumber() uint64 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

type NonceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonceResponse) Reset() {
	*x = NonceResponse{}
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonceResponse) ProtoMessage() {}

func (x *NonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_endorsement_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonceResponse.ProtoReflect.Descriptor instead.
func (*NonceResponse) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_endorsement_proto_rawDescGZIP(), []int{11}
}

func (x *NonceResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_api_endorsementpb_endorsement_proto protoreflect.FileDescriptor

const file_api_endorsementpb_endorsement_proto_rawDesc = "" +
	"\n" +
	"#api/endorsementpb/endorsement.proto\x12\rendorsementpb\"V\n" +
	"\x0eExecuteRequest\x12\x1f\n" +
	"\vethereum_tx\x18\x01 \x01(\fR\n" +
	"ethereumTx\x12#\n" +
	"\rproposal_hash\x18\x02 \x01(\fR\fproposalHash\"\xd8\x01\n" +
	"\x0fExecuteResponse\x12$\n" +
	"\x0eread_write_set\x18\x01 \x01(\fR\freadWriteSet\x12\x14\n" +
	"\x05event\x18\x02 \x01(\fR\x05event\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1f\n" +
	"\vendorser_id\x18\x06 \x01(\fR\n" +
	"endorserId\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\"\xc3\x01\n" +
	"\vCallRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\fR\x02to\x12\x10\n" +
	"\x03gas\x18\x03 \x01(\x04R\x03gas\x12\x1b\n" +
	"\tgas_price\x18\x04 \x01(\fR\bgasPrice\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12&\n" +
	"\fblock_number\x18\a \x01(\x04H\x00R\vblockNumber\x88\x01\x01B\x0f\n" +
	"\r_block_number\"a\n" +
	"\fCallResponse\x12\x1f\n" +
	"\vreturn_data\x18\x01 \x01(\fR\n" +
	"returnData\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"c\n" +
	"\x0eBalanceRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\fR\aaccount\x12&\n" +
	"\fblock_number\x18\x02 \x01(\x04H\x00R\vblockNumber\x88\x01\x01B\x0f\n" +
	"\r_block_number\"+\n" +
	"\x0fBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\fR\abalance\"u\n" +
	"\x0eStorageRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\fR\aaccount\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12&\n" +
	"\fblock_number\x18\x03 \x01(\x04H\x00R\vblockNumber\x88\x01\x01B\x0f\n" +
	"\r_block_number\"'\n" +
	"\x0fStorageResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"`\n" +
	"\vCodeRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\fR\aaccount\x12&\n" +
	"\fblock_number\x18\x02 \x01(\x04H\x00R\vblockNumber\x88\x01\x01B\x0f\n" +
	"\r_block_number\"\"\n" +
	"\fCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\fR\x04code\"a\n" +
	"\fNonceRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\fR\aaccount\x12&\n" +
	"\fblock_number\x18\x02 \x01(\x04H\x00R\vblockNumber\x88\x01\x01B\x0f\n" +
	"\r_block_number\"%\n" +
	"\rNonceResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce2\xc8\x03\n" +
	"\x0eEvmEndorsement\x12J\n" +
	"\aExecute\x12\x1d.endorsementpb.ExecuteRequest\x1a\x1e.endorsementpb.ExecuteResponse\"\x00\x12A\n" +
	"\x04Call\x12\x1a.endorsementpb.CallRequest\x1a\x1b.endorsementpb.CallResponse\"\x00\x12L\n" +
	"\tBalanceAt\x12\x1d.endorsementpb.BalanceRequest\x1a\x1e.endorsementpb.BalanceResponse\"\x00\x12L\n" +
	"\tStorageAt\x12\x1d.endorsementpb.StorageRequest\x1a\x1e.endorsementpb.StorageResponse\"\x00\x12C\n" +
	"\x06CodeAt\x12\x1a.endorsementpb.CodeRequest\x1a\x1b.endorsementpb.CodeResponse\"\x00\x12F\n" +
	"\aNonceAt\x12\x1b.endorsementpb.NonceRequest\x1a\x1c.endorsementpb.NonceResponse\"\x00B7Z5github.com/hyperledger/fabric-x-evm/api/endorsementpbb\x06proto3"

var (
	file_api_endorsementpb_endorsement_proto_rawDescOnce sync.Once
	file_api_endorsementpb_endorsement_proto_rawDescData []byte
)

func file_api_endorsementpb_endorsement_proto_rawDescGZIP() []byte {
	file_api_endorsementpb_endorsement_proto_rawDescOnce.Do(func() {
		file_api_endorsementpb_endorsement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_endorsementpb_endorsement_proto_rawDesc), len(file_api_endorsementpb_endorsement_proto_rawDesc)))
	})
	return file_api_endorsementpb_endorsement_proto_rawDescData
}

var file_api_endorsementpb_endorsement_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_endorsementpb_endorsement_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: endorsementpb.ExecuteRequest
	(*ExecuteResponse)(nil), // 1: endorsementpb.ExecuteResponse
	(*CallRequest)(nil),     // 2: endorsementpb.CallRequest
	(*CallResponse)(nil),    // 3: endorsementpb.CallResponse
	(*BalanceRequest)(nil),  // 4: endorsementpb.BalanceRequest
	(*BalanceResponse)(nil), // 5: endorsementpb.BalanceResponse
	(*StorageRequest)(nil),  // 6: endorsementpb.StorageRequest
	(*StorageResponse)(nil), // 7: endorsementpb.StorageResponse
	(*CodeRequest)(nil),     // 8: endorsementpb.CodeRequest
	(*CodeResponse)(nil),    // 9: endorsementpb.CodeResponse
	(*NonceRequest)(nil),    // 10: endorsementpb.NonceRequest
	(*NonceResponse)(nil),   // 11: endorsementpb.NonceResponse
}
var file_api_endorsementpb_endorsement_proto_depIdxs = []int32{
	0,  // 0: endorsementpb.EvmEndorsement.Execute:input_type -> endorsementpb.ExecuteRequest
	2,  // 1: endorsementpb.EvmEndorsement.Call:input_type -> endorsementpb.CallRequest
	4,  // 2: endorsementpb.EvmEndorsement.BalanceAt:input_type -> endorsementpb.BalanceRequest
	6,  // 3: endorsementpb.EvmEndorsement.StorageAt:input_type -> endorsementpb.StorageRequest
	8,  // 4: endorsementpb.EvmEndorsement.CodeAt:input_type -> endorsementpb.CodeRequest
	10, // 5: endorsementpb.EvmEndorsement.NonceAt:input_type -> endorsementpb.NonceRequest
	1,  // 6: endorsementpb.EvmEndorsement.Execute:output_type -> endorsementpb.ExecuteResponse
	3,  // 7: endorsementpb.EvmEndorsement.Call:output_type -> endorsementpb.CallResponse
	5,  // 8: endorsementpb.EvmEndorsement.BalanceAt:output_type -> endorsementpb.BalanceResponse
	7,  // 9: endorsementpb.EvmEndorsement.StorageAt:output_type -> endorsementpb.StorageResponse
	9,  // 10: endorsementpb.EvmEndorsement.CodeAt:output_type -> endorsementpb.CodeResponse
	11, // 11: endorsementpb.EvmEndorsement.NonceAt:output_type -> endorsementpb.NonceResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_endorsementpb_endorsement_proto_init() }
func file_api_endorsementpb_endorsement_proto_init() {
	if File_api_endorsementpb_endorsement_proto != nil {
		return
	}
	file_api_endorsementpb_endorsement_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_endorsementpb_endorsement_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_endorsementpb_endorsement_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_endorsementpb_endorsement_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_endorsementpb_endorsement_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_endorsementpb_endorsement_proto_rawDesc), len(file_api_endorsementpb_endorsement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_endorsementpb_endorsement_proto_goTypes,
		DependencyIndexes: file_api_endorsementpb_endorsement_proto_depIdxs,
		MessageInfos:      file_api_endorsementpb_endorsement_proto_msgTypes,
	}.Build()
	File_api_endorsementpb_endorsement_proto = out.File
	file_api_endorsementpb_endorsement_proto_goTypes = nil
	file_api_endorsementpb_endorsement_proto_depIdxs = nil
}
