//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: LGPL-3.0-or-later

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: api/endorsementpb/execution.proto

package endorsementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecutionStatus is the outcome of executing an EVM transaction.
type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_SUCCESS     ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_REVERTED    ExecutionStatus = 2
	// Valid transaction whose execution failed without reverting (out of gas,
	// invalid opcode, ...).
	ExecutionStatus_EXECUTION_STATUS_EXEC_FAILED ExecutionStatus = 3
	// Invalid transaction, rejected before execution. Never written on-chain,
	// since a rejected transaction is not submitted; reserved for completeness.
	ExecutionStatus_EXECUTION_STATUS_REJECTED ExecutionStatus = 4
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_SUCCESS",
		2: "EXECUTION_STATUS_REVERTED",
		3: "EXECUTION_STATUS_EXEC_FAILED",
		4: "EXECUTION_STATUS_REJECTED",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"EXECUTION_STATUS_SUCCESS":     1,
		"EXECUTION_STATUS_REVERTED":    2,
		"EXECUTION_STATUS_EXEC_FAILED": 3,
		"EXECUTION_STATUS_REJECTED":    4,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_endorsementpb_execution_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_api_endorsementpb_execution_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_endorsementpb_execution_proto_rawDescGZIP(), []int{0}
}

// ExecutionMetadata is the execution outcome the endorser stores in the
// transaction Payload.
type ExecutionMetadata struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status ExecutionStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=endorsementpb.ExecutionStatus" json:"status,omitempty"`
	// Revert return data for a revert; empty otherwise.
	Reason []byte `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// EVM gas used, after refunds.
	GasUsed uint64 `protobuf:"varint,3,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	// Unix seconds the transaction executed at (EVM block.timestamp).
	Timestamp     uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionMetadata) Reset() {
	*x = ExecutionMetadata{}
	mi := &file_api_endorsementpb_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionMetadata) ProtoMessage() {}

func (x *ExecutionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_endorsementpb_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionMetadata.ProtoReflect.Descriptor instead.
func (*ExecutionMetadata) Descriptor() ([]byte, []int) {
	return file_api_endorsementpb_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionMetadata) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ExecutionMetadata) GetReason() []byte {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *ExecutionMetadata) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionMetadata) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_endorsementpb_execution_proto protoreflect.FileDescriptor

const file_api_endorsementpb_execution_proto_rawDesc = "" +
	"\n" +
	"!api/endorsementpb/execution.proto\x12\rendorsementpb\"\x9c\x01\n" +
	"\x11ExecutionMetadata\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.endorsementpb.ExecutionStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\fR\x06reason\x12\x19\n" +
	"\bgas_used\x18\x03 \x01(\x04R\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp*\xb1\x01\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EXECUTION_STATUS_SUCCESS\x10\x01\x12\x1d\n" +
	"\x19EXECUTION_STATUS_REVERTED\x10\x02\x12 \n" +
	"\x1cEXECUTION_STATUS_EXEC_FAILED\x10\x03\x12\x1d\n" +
	"\x19EXECUTION_STATUS_REJECTED\x10\x04B7Z5github.com/hyperledger/fabric-x-evm/api/endorsementpbb\x06proto3"

var (
	file_api_endorsementpb_execution_proto_rawDescOnce sync.Once
	file_api_endorsementpb_execution_proto_rawDescData []byte
)

func file_api_endorsementpb_execution_proto_rawDescGZIP() []byte {
	file_api_endorsementpb_execution_proto_rawDescOnce.Do(func() {
		file_api_endorsementpb_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_endorsementpb_execution_proto_rawDesc), len(file_api_endorsementpb_execution_proto_rawDesc)))
	})
	return file_api_endorsementpb_execution_proto_rawDescData
}

var file_api_endorsementpb_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_endorsementpb_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_endorsementpb_execution_proto_goTypes = []any{
	(ExecutionStatus)(0),      // 0: endorsementpb.ExecutionStatus
	(*ExecutionMetadata)(nil), // 1: endorsementpb.ExecutionMetadata
}
var file_api_endorsementpb_execution_proto_depIdxs = []int32{
	0, // 0: endorsementpb.ExecutionMetadata.status:type_name -> endorsementpb.ExecutionStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_endorsementpb_execution_proto_init() }
func file_api_endorsementpb_execution_proto_init() {
	if File_api_endorsementpb_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_endorsementpb_execution_proto_rawDesc), len(file_api_endorsementpb_execution_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_endorsementpb_execution_proto_goTypes,
		DependencyIndexes: file_api_endorsementpb_execution_proto_depIdxs,
		EnumInfos:         file_api_endorsementpb_execution_proto_enumTypes,
		MessageInfos:      file_api_endorsementpb_execution_proto_msgTypes,
	}.Build()
	File_api_endorsementpb_execution_proto = out.File
	file_api_endorsementpb_execution_proto_goTypes = nil
	file_api_endorsementpb_execution_proto_depIdxs = nil
}
